//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MBSModel", "FK_Booking_ShowTime", "ShowTime", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MBSDAL.ShowTime), "Booking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.Booking), true)]
[assembly: EdmRelationshipAttribute("MBSModel", "FK_FoodOrder_Booking", "Booking", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MBSDAL.Booking), "FoodOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.FoodOrder), true)]
[assembly: EdmRelationshipAttribute("MBSModel", "FK_Screen_Cinema", "Cinema", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MBSDAL.Cinema), "Screen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.Screen), true)]
[assembly: EdmRelationshipAttribute("MBSModel", "FK_MovieSchedule_Screen", "Movie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MBSDAL.Movie), "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.MovieSchedule), true)]
[assembly: EdmRelationshipAttribute("MBSModel", "FK_MovieSchedule_Screen1", "Screen", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MBSDAL.Screen), "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.MovieSchedule), true)]
[assembly: EdmRelationshipAttribute("MBSModel", "FK_ShowTime_MovieSchedule", "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MBSDAL.MovieSchedule), "ShowTime", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MBSDAL.ShowTime), true)]

#endregion

namespace MBSDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MBS_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MBS_Entities object using the connection string found in the 'MBS_Entities' section of the application configuration file.
        /// </summary>
        public MBS_Entities() : base("name=MBS_Entities", "MBS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MBS_Entities object.
        /// </summary>
        public MBS_Entities(string connectionString) : base(connectionString, "MBS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MBS_Entities object.
        /// </summary>
        public MBS_Entities(EntityConnection connection) : base(connection, "MBS_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Booking> Bookings
        {
            get
            {
                if ((_Bookings == null))
                {
                    _Bookings = base.CreateObjectSet<Booking>("Bookings");
                }
                return _Bookings;
            }
        }
        private ObjectSet<Booking> _Bookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cinema> Cinemas
        {
            get
            {
                if ((_Cinemas == null))
                {
                    _Cinemas = base.CreateObjectSet<Cinema>("Cinemas");
                }
                return _Cinemas;
            }
        }
        private ObjectSet<Cinema> _Cinemas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Food> Foods
        {
            get
            {
                if ((_Foods == null))
                {
                    _Foods = base.CreateObjectSet<Food>("Foods");
                }
                return _Foods;
            }
        }
        private ObjectSet<Food> _Foods;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FoodOrder> FoodOrders
        {
            get
            {
                if ((_FoodOrders == null))
                {
                    _FoodOrders = base.CreateObjectSet<FoodOrder>("FoodOrders");
                }
                return _FoodOrders;
            }
        }
        private ObjectSet<FoodOrder> _FoodOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MovieSchedule> MovieSchedules
        {
            get
            {
                if ((_MovieSchedules == null))
                {
                    _MovieSchedules = base.CreateObjectSet<MovieSchedule>("MovieSchedules");
                }
                return _MovieSchedules;
            }
        }
        private ObjectSet<MovieSchedule> _MovieSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Screen> Screens
        {
            get
            {
                if ((_Screens == null))
                {
                    _Screens = base.CreateObjectSet<Screen>("Screens");
                }
                return _Screens;
            }
        }
        private ObjectSet<Screen> _Screens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShowTime> ShowTimes
        {
            get
            {
                if ((_ShowTimes == null))
                {
                    _ShowTimes = base.CreateObjectSet<ShowTime>("ShowTimes");
                }
                return _ShowTimes;
            }
        }
        private ObjectSet<ShowTime> _ShowTimes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookings(Booking booking)
        {
            base.AddObject("Bookings", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cinemas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCinemas(Cinema cinema)
        {
            base.AddObject("Cinemas", cinema);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Foods EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoods(Food food)
        {
            base.AddObject("Foods", food);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FoodOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFoodOrders(FoodOrder foodOrder)
        {
            base.AddObject("FoodOrders", foodOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MovieSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovieSchedules(MovieSchedule movieSchedule)
        {
            base.AddObject("MovieSchedules", movieSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Screens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScreens(Screen screen)
        {
            base.AddObject("Screens", screen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShowTimes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShowTimes(ShowTime showTime)
        {
            base.AddObject("ShowTimes", showTime);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="Booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Booking object.
        /// </summary>
        /// <param name="bookingID">Initial value of the BookingID property.</param>
        public static Booking CreateBooking(global::System.Int32 bookingID)
        {
            Booking booking = new Booking();
            booking.BookingID = bookingID;
            return booking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BookingID
        {
            get
            {
                return _BookingID;
            }
            set
            {
                if (_BookingID != value)
                {
                    OnBookingIDChanging(value);
                    ReportPropertyChanging("BookingID");
                    _BookingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookingID");
                    OnBookingIDChanged();
                }
            }
        }
        private global::System.Int32 _BookingID;
        partial void OnBookingIDChanging(global::System.Int32 value);
        partial void OnBookingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BookingDate
        {
            get
            {
                return _BookingDate;
            }
            set
            {
                OnBookingDateChanging(value);
                ReportPropertyChanging("BookingDate");
                _BookingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookingDate");
                OnBookingDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BookingDate;
        partial void OnBookingDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBookingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Seatnumbers
        {
            get
            {
                return _Seatnumbers;
            }
            set
            {
                OnSeatnumbersChanging(value);
                ReportPropertyChanging("Seatnumbers");
                _Seatnumbers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Seatnumbers");
                OnSeatnumbersChanged();
            }
        }
        private global::System.String _Seatnumbers;
        partial void OnSeatnumbersChanging(global::System.String value);
        partial void OnSeatnumbersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RewardPointsGained
        {
            get
            {
                return _RewardPointsGained;
            }
            set
            {
                OnRewardPointsGainedChanging(value);
                ReportPropertyChanging("RewardPointsGained");
                _RewardPointsGained = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RewardPointsGained");
                OnRewardPointsGainedChanged();
            }
        }
        private Nullable<global::System.Int32> _RewardPointsGained;
        partial void OnRewardPointsGainedChanging(Nullable<global::System.Int32> value);
        partial void OnRewardPointsGainedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShowTimeID
        {
            get
            {
                return _ShowTimeID;
            }
            set
            {
                OnShowTimeIDChanging(value);
                ReportPropertyChanging("ShowTimeID");
                _ShowTimeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowTimeID");
                OnShowTimeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ShowTimeID;
        partial void OnShowTimeIDChanging(Nullable<global::System.Int32> value);
        partial void OnShowTimeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnUserIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_Booking_ShowTime", "ShowTime")]
        public ShowTime ShowTime
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShowTime>("MBSModel.FK_Booking_ShowTime", "ShowTime").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShowTime>("MBSModel.FK_Booking_ShowTime", "ShowTime").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShowTime> ShowTimeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShowTime>("MBSModel.FK_Booking_ShowTime", "ShowTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShowTime>("MBSModel.FK_Booking_ShowTime", "ShowTime", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_FoodOrder_Booking", "FoodOrder")]
        public EntityCollection<FoodOrder> FoodOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FoodOrder>("MBSModel.FK_FoodOrder_Booking", "FoodOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FoodOrder>("MBSModel.FK_FoodOrder_Booking", "FoodOrder", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="Cinema")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cinema : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cinema object.
        /// </summary>
        /// <param name="cinemaID">Initial value of the CinemaID property.</param>
        public static Cinema CreateCinema(global::System.Int32 cinemaID)
        {
            Cinema cinema = new Cinema();
            cinema.CinemaID = cinemaID;
            return cinema;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CinemaID
        {
            get
            {
                return _CinemaID;
            }
            set
            {
                if (_CinemaID != value)
                {
                    OnCinemaIDChanging(value);
                    ReportPropertyChanging("CinemaID");
                    _CinemaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CinemaID");
                    OnCinemaIDChanged();
                }
            }
        }
        private global::System.Int32 _CinemaID;
        partial void OnCinemaIDChanging(global::System.Int32 value);
        partial void OnCinemaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CinemaName
        {
            get
            {
                return _CinemaName;
            }
            set
            {
                OnCinemaNameChanging(value);
                ReportPropertyChanging("CinemaName");
                _CinemaName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CinemaName");
                OnCinemaNameChanged();
            }
        }
        private global::System.String _CinemaName;
        partial void OnCinemaNameChanging(global::System.String value);
        partial void OnCinemaNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumOfScreens
        {
            get
            {
                return _NumOfScreens;
            }
            set
            {
                OnNumOfScreensChanging(value);
                ReportPropertyChanging("NumOfScreens");
                _NumOfScreens = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOfScreens");
                OnNumOfScreensChanged();
            }
        }
        private Nullable<global::System.Int32> _NumOfScreens;
        partial void OnNumOfScreensChanging(Nullable<global::System.Int32> value);
        partial void OnNumOfScreensChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_Screen_Cinema", "Screen")]
        public EntityCollection<Screen> Screens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Screen>("MBSModel.FK_Screen_Cinema", "Screen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Screen>("MBSModel.FK_Screen_Cinema", "Screen", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="Food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Food : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Food object.
        /// </summary>
        /// <param name="foodID">Initial value of the FoodID property.</param>
        public static Food CreateFood(global::System.Int32 foodID)
        {
            Food food = new Food();
            food.FoodID = foodID;
            return food;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FoodID
        {
            get
            {
                return _FoodID;
            }
            set
            {
                if (_FoodID != value)
                {
                    OnFoodIDChanging(value);
                    ReportPropertyChanging("FoodID");
                    _FoodID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FoodID");
                    OnFoodIDChanged();
                }
            }
        }
        private global::System.Int32 _FoodID;
        partial void OnFoodIDChanging(global::System.Int32 value);
        partial void OnFoodIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="FoodOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FoodOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FoodOrder object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        public static FoodOrder CreateFoodOrder(global::System.Int32 orderID)
        {
            FoodOrder foodOrder = new FoodOrder();
            foodOrder.OrderID = orderID;
            return foodOrder;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BookingID
        {
            get
            {
                return _BookingID;
            }
            set
            {
                OnBookingIDChanging(value);
                ReportPropertyChanging("BookingID");
                _BookingID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookingID");
                OnBookingIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BookingID;
        partial void OnBookingIDChanging(Nullable<global::System.Int32> value);
        partial void OnBookingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemsOrdered
        {
            get
            {
                return _ItemsOrdered;
            }
            set
            {
                OnItemsOrderedChanging(value);
                ReportPropertyChanging("ItemsOrdered");
                _ItemsOrdered = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemsOrdered");
                OnItemsOrderedChanged();
            }
        }
        private global::System.String _ItemsOrdered;
        partial void OnItemsOrderedChanging(global::System.String value);
        partial void OnItemsOrderedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amount;
        partial void OnAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAmountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_FoodOrder_Booking", "Booking")]
        public Booking Booking
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("MBSModel.FK_FoodOrder_Booking", "Booking").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("MBSModel.FK_FoodOrder_Booking", "Booking").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Booking> BookingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("MBSModel.FK_FoodOrder_Booking", "Booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Booking>("MBSModel.FK_FoodOrder_Booking", "Booking", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="movieID">Initial value of the MovieID property.</param>
        public static Movie CreateMovie(global::System.Int32 movieID)
        {
            Movie movie = new Movie();
            movie.MovieID = movieID;
            return movie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MovieID
        {
            get
            {
                return _MovieID;
            }
            set
            {
                if (_MovieID != value)
                {
                    OnMovieIDChanging(value);
                    ReportPropertyChanging("MovieID");
                    _MovieID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MovieID");
                    OnMovieIDChanged();
                }
            }
        }
        private global::System.Int32 _MovieID;
        partial void OnMovieIDChanging(global::System.Int32 value);
        partial void OnMovieIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MovieTitle
        {
            get
            {
                return _MovieTitle;
            }
            set
            {
                OnMovieTitleChanging(value);
                ReportPropertyChanging("MovieTitle");
                _MovieTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MovieTitle");
                OnMovieTitleChanged();
            }
        }
        private global::System.String _MovieTitle;
        partial void OnMovieTitleChanging(global::System.String value);
        partial void OnMovieTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.Int32> _Duration;
        partial void OnDurationChanging(Nullable<global::System.Int32> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Genre
        {
            get
            {
                return _Genre;
            }
            set
            {
                OnGenreChanging(value);
                ReportPropertyChanging("Genre");
                _Genre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Genre");
                OnGenreChanged();
            }
        }
        private global::System.String _Genre;
        partial void OnGenreChanging(global::System.String value);
        partial void OnGenreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cast
        {
            get
            {
                return _Cast;
            }
            set
            {
                OnCastChanging(value);
                ReportPropertyChanging("Cast");
                _Cast = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cast");
                OnCastChanged();
            }
        }
        private global::System.String _Cast;
        partial void OnCastChanging(global::System.String value);
        partial void OnCastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private Nullable<global::System.Double> _Rating;
        partial void OnRatingChanging(Nullable<global::System.Double> value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReleaseDate
        {
            get
            {
                return _ReleaseDate;
            }
            set
            {
                OnReleaseDateChanging(value);
                ReportPropertyChanging("ReleaseDate");
                _ReleaseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReleaseDate");
                OnReleaseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReleaseDate;
        partial void OnReleaseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReleaseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_MovieSchedule_Screen", "MovieSchedule")]
        public EntityCollection<MovieSchedule> MovieSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MovieSchedule>("MBSModel.FK_MovieSchedule_Screen", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MovieSchedule>("MBSModel.FK_MovieSchedule_Screen", "MovieSchedule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="MovieSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MovieSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MovieSchedule object.
        /// </summary>
        /// <param name="movieScheduleID">Initial value of the MovieScheduleID property.</param>
        public static MovieSchedule CreateMovieSchedule(global::System.Int32 movieScheduleID)
        {
            MovieSchedule movieSchedule = new MovieSchedule();
            movieSchedule.MovieScheduleID = movieScheduleID;
            return movieSchedule;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MovieScheduleID
        {
            get
            {
                return _MovieScheduleID;
            }
            set
            {
                if (_MovieScheduleID != value)
                {
                    OnMovieScheduleIDChanging(value);
                    ReportPropertyChanging("MovieScheduleID");
                    _MovieScheduleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MovieScheduleID");
                    OnMovieScheduleIDChanged();
                }
            }
        }
        private global::System.Int32 _MovieScheduleID;
        partial void OnMovieScheduleIDChanging(global::System.Int32 value);
        partial void OnMovieScheduleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ShowStartTime
        {
            get
            {
                return _ShowStartTime;
            }
            set
            {
                OnShowStartTimeChanging(value);
                ReportPropertyChanging("ShowStartTime");
                _ShowStartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowStartTime");
                OnShowStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ShowStartTime;
        partial void OnShowStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnShowStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ShowEndTime
        {
            get
            {
                return _ShowEndTime;
            }
            set
            {
                OnShowEndTimeChanging(value);
                ReportPropertyChanging("ShowEndTime");
                _ShowEndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowEndTime");
                OnShowEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ShowEndTime;
        partial void OnShowEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnShowEndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> WeekDateFare
        {
            get
            {
                return _WeekDateFare;
            }
            set
            {
                OnWeekDateFareChanging(value);
                ReportPropertyChanging("WeekDateFare");
                _WeekDateFare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekDateFare");
                OnWeekDateFareChanged();
            }
        }
        private Nullable<global::System.Decimal> _WeekDateFare;
        partial void OnWeekDateFareChanging(Nullable<global::System.Decimal> value);
        partial void OnWeekDateFareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> WeekEndFare
        {
            get
            {
                return _WeekEndFare;
            }
            set
            {
                OnWeekEndFareChanging(value);
                ReportPropertyChanging("WeekEndFare");
                _WeekEndFare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WeekEndFare");
                OnWeekEndFareChanged();
            }
        }
        private Nullable<global::System.Decimal> _WeekEndFare;
        partial void OnWeekEndFareChanging(Nullable<global::System.Decimal> value);
        partial void OnWeekEndFareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CinemaID
        {
            get
            {
                return _CinemaID;
            }
            set
            {
                OnCinemaIDChanging(value);
                ReportPropertyChanging("CinemaID");
                _CinemaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CinemaID");
                OnCinemaIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CinemaID;
        partial void OnCinemaIDChanging(Nullable<global::System.Int32> value);
        partial void OnCinemaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScreenNo
        {
            get
            {
                return _ScreenNo;
            }
            set
            {
                OnScreenNoChanging(value);
                ReportPropertyChanging("ScreenNo");
                _ScreenNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScreenNo");
                OnScreenNoChanged();
            }
        }
        private Nullable<global::System.Int32> _ScreenNo;
        partial void OnScreenNoChanging(Nullable<global::System.Int32> value);
        partial void OnScreenNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MovieID
        {
            get
            {
                return _MovieID;
            }
            set
            {
                OnMovieIDChanging(value);
                ReportPropertyChanging("MovieID");
                _MovieID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MovieID");
                OnMovieIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MovieID;
        partial void OnMovieIDChanging(Nullable<global::System.Int32> value);
        partial void OnMovieIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_MovieSchedule_Screen", "Movie")]
        public Movie Movie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MBSModel.FK_MovieSchedule_Screen", "Movie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MBSModel.FK_MovieSchedule_Screen", "Movie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movie> MovieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("MBSModel.FK_MovieSchedule_Screen", "Movie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movie>("MBSModel.FK_MovieSchedule_Screen", "Movie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_MovieSchedule_Screen1", "Screen")]
        public Screen Screen
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Screen>("MBSModel.FK_MovieSchedule_Screen1", "Screen").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Screen>("MBSModel.FK_MovieSchedule_Screen1", "Screen").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Screen> ScreenReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Screen>("MBSModel.FK_MovieSchedule_Screen1", "Screen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Screen>("MBSModel.FK_MovieSchedule_Screen1", "Screen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_ShowTime_MovieSchedule", "ShowTime")]
        public EntityCollection<ShowTime> ShowTimes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ShowTime>("MBSModel.FK_ShowTime_MovieSchedule", "ShowTime");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ShowTime>("MBSModel.FK_ShowTime_MovieSchedule", "ShowTime", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="Screen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Screen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Screen object.
        /// </summary>
        /// <param name="cinemaID">Initial value of the CinemaID property.</param>
        /// <param name="screenNo">Initial value of the ScreenNo property.</param>
        public static Screen CreateScreen(global::System.Int32 cinemaID, global::System.Int32 screenNo)
        {
            Screen screen = new Screen();
            screen.CinemaID = cinemaID;
            screen.ScreenNo = screenNo;
            return screen;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CinemaID
        {
            get
            {
                return _CinemaID;
            }
            set
            {
                if (_CinemaID != value)
                {
                    OnCinemaIDChanging(value);
                    ReportPropertyChanging("CinemaID");
                    _CinemaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CinemaID");
                    OnCinemaIDChanged();
                }
            }
        }
        private global::System.Int32 _CinemaID;
        partial void OnCinemaIDChanging(global::System.Int32 value);
        partial void OnCinemaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScreenNo
        {
            get
            {
                return _ScreenNo;
            }
            set
            {
                if (_ScreenNo != value)
                {
                    OnScreenNoChanging(value);
                    ReportPropertyChanging("ScreenNo");
                    _ScreenNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScreenNo");
                    OnScreenNoChanged();
                }
            }
        }
        private global::System.Int32 _ScreenNo;
        partial void OnScreenNoChanging(global::System.Int32 value);
        partial void OnScreenNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumOfSeats
        {
            get
            {
                return _NumOfSeats;
            }
            set
            {
                OnNumOfSeatsChanging(value);
                ReportPropertyChanging("NumOfSeats");
                _NumOfSeats = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumOfSeats");
                OnNumOfSeatsChanged();
            }
        }
        private Nullable<global::System.Int32> _NumOfSeats;
        partial void OnNumOfSeatsChanging(Nullable<global::System.Int32> value);
        partial void OnNumOfSeatsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_Screen_Cinema", "Cinema")]
        public Cinema Cinema
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cinema>("MBSModel.FK_Screen_Cinema", "Cinema").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cinema>("MBSModel.FK_Screen_Cinema", "Cinema").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cinema> CinemaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cinema>("MBSModel.FK_Screen_Cinema", "Cinema");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cinema>("MBSModel.FK_Screen_Cinema", "Cinema", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_MovieSchedule_Screen1", "MovieSchedule")]
        public EntityCollection<MovieSchedule> MovieSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MovieSchedule>("MBSModel.FK_MovieSchedule_Screen1", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MovieSchedule>("MBSModel.FK_MovieSchedule_Screen1", "MovieSchedule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="ShowTime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShowTime : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShowTime object.
        /// </summary>
        /// <param name="showID">Initial value of the ShowID property.</param>
        public static ShowTime CreateShowTime(global::System.Int32 showID)
        {
            ShowTime showTime = new ShowTime();
            showTime.ShowID = showID;
            return showTime;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShowID
        {
            get
            {
                return _ShowID;
            }
            set
            {
                if (_ShowID != value)
                {
                    OnShowIDChanging(value);
                    ReportPropertyChanging("ShowID");
                    _ShowID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ShowID");
                    OnShowIDChanged();
                }
            }
        }
        private global::System.Int32 _ShowID;
        partial void OnShowIDChanging(global::System.Int32 value);
        partial void OnShowIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Fare
        {
            get
            {
                return _Fare;
            }
            set
            {
                OnFareChanging(value);
                ReportPropertyChanging("Fare");
                _Fare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fare");
                OnFareChanged();
            }
        }
        private Nullable<global::System.Decimal> _Fare;
        partial void OnFareChanging(Nullable<global::System.Decimal> value);
        partial void OnFareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ShowDate
        {
            get
            {
                return _ShowDate;
            }
            set
            {
                OnShowDateChanging(value);
                ReportPropertyChanging("ShowDate");
                _ShowDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShowDate");
                OnShowDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ShowDate;
        partial void OnShowDateChanging(Nullable<global::System.DateTime> value);
        partial void OnShowDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SeatsAvailable
        {
            get
            {
                return _SeatsAvailable;
            }
            set
            {
                OnSeatsAvailableChanging(value);
                ReportPropertyChanging("SeatsAvailable");
                _SeatsAvailable = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SeatsAvailable");
                OnSeatsAvailableChanged();
            }
        }
        private global::System.String _SeatsAvailable;
        partial void OnSeatsAvailableChanging(global::System.String value);
        partial void OnSeatsAvailableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MovieScheduleID
        {
            get
            {
                return _MovieScheduleID;
            }
            set
            {
                OnMovieScheduleIDChanging(value);
                ReportPropertyChanging("MovieScheduleID");
                _MovieScheduleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MovieScheduleID");
                OnMovieScheduleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MovieScheduleID;
        partial void OnMovieScheduleIDChanging(Nullable<global::System.Int32> value);
        partial void OnMovieScheduleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_Booking_ShowTime", "Booking")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("MBSModel.FK_Booking_ShowTime", "Booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("MBSModel.FK_Booking_ShowTime", "Booking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MBSModel", "FK_ShowTime_MovieSchedule", "MovieSchedule")]
        public MovieSchedule MovieSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("MBSModel.FK_ShowTime_MovieSchedule", "MovieSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("MBSModel.FK_ShowTime_MovieSchedule", "MovieSchedule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MovieSchedule> MovieScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("MBSModel.FK_ShowTime_MovieSchedule", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MovieSchedule>("MBSModel.FK_ShowTime_MovieSchedule", "MovieSchedule", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MBSModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static User CreateUser(global::System.Int32 userID)
        {
            User user = new User();
            user.UserID = userID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.String _IsDeleted;
        partial void OnIsDeletedChanging(global::System.String value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private Nullable<global::System.Int64> _Contact;
        partial void OnContactChanging(Nullable<global::System.Int64> value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalRewardPoints
        {
            get
            {
                return _TotalRewardPoints;
            }
            set
            {
                OnTotalRewardPointsChanging(value);
                ReportPropertyChanging("TotalRewardPoints");
                _TotalRewardPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRewardPoints");
                OnTotalRewardPointsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalRewardPoints;
        partial void OnTotalRewardPointsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalRewardPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Preferences
        {
            get
            {
                return _Preferences;
            }
            set
            {
                OnPreferencesChanging(value);
                ReportPropertyChanging("Preferences");
                _Preferences = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Preferences");
                OnPreferencesChanged();
            }
        }
        private global::System.String _Preferences;
        partial void OnPreferencesChanging(global::System.String value);
        partial void OnPreferencesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserNotified
        {
            get
            {
                return _UserNotified;
            }
            set
            {
                OnUserNotifiedChanging(value);
                ReportPropertyChanging("UserNotified");
                _UserNotified = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserNotified");
                OnUserNotifiedChanged();
            }
        }
        private global::System.String _UserNotified;
        partial void OnUserNotifiedChanging(global::System.String value);
        partial void OnUserNotifiedChanged();

        #endregion
    
    }

    #endregion
    
}
